"""Generate js/test/fixtures/adapter-parity-synthetic.json — the COMMITTED half of the
adapter cross-language parity gate.

WHY THIS EXISTS ALONGSIDE tools/gen-adapter-parity.py.

    tools/gen-adapter-parity.py writes js/test/fixtures/adapter-parity.json, which SAMPLES
    the owner's real private corpora. That file is gitignored (.gitignore:32) and is
    generated by no workflow, so on every fresh clone and in every CI run it is ABSENT --
    and adapter-parity.test.ts guarded its whole suite with describe.skipIf(!present).
    The result was a gate that had never once executed anywhere except one machine: it
    could not fail, so it was indistinguishable from no gate at all.

    This generator is the corpus-free twin. Every input below is INVENTED -- no real
    conversation content, nothing sampled from any export -- so its output is safe to
    commit, ships with the clone, and makes the parity suite fail-closed. The real-corpus
    fixture is still layered on top when it happens to be present locally.

WHAT IT CAPTURES. For each provider, BOTH the raw export input AND the IR the PYTHON
adapter produced from it. The JS test feeds the identical input to the JS adapter and
asserts identical IR. That is what reaches the logic the synthetic renderer fixtures never
touch: Claude's subtree-max active-path walk (the naive version dropped 42 messages on real
data), ChatGPT's current_node fallback and branch bookkeeping, epoch->ISO timestamp
formatting, and the content-type dispatch.

REGENERATE (from the repo root, no install and no corpus needed):

    python js/test/fixtures/gen-adapter-parity-synthetic.py

The CI js job runs exactly that and then `git diff --exit-code` on the output, so a change
to a PYTHON adapter that this rail has not matched turns the js job red at its source.
"""
import dataclasses
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
sys.path.insert(0, ROOT)

from llm_anthology.adapters import chatgpt, claude, gemini  # noqa: E402

OUT = os.path.join(HERE, "adapter-parity-synthetic.json")


def ir_dict(conv):
    return dataclasses.asdict(conv)


# ------------------------------------------------------------------------------- claude

def _cmsg(uuid, parent, sender, text, ts, **extra):
    m = {"uuid": uuid, "parent_message_uuid": parent, "sender": sender, "created_at": ts,
         "content": [{"type": "text", "text": text, "citations": []}],
         "attachments": [], "files": [], "text": ""}
    m.update(extra)
    return m


def claude_cases():
    # The shape that dropped 42 messages before the active-path walk picked the subtree
    # with the deepest continuation: two roots (one whose parent is not in the export at
    # all) plus a branch point where the ABANDONED reply is the one listed first.
    yield "synthetic-multiroot", {
        "uuid": "c", "name": "multi", "account": {"uuid": "a"},
        "chat_messages": [
            _cmsg("r1", None, "human", "root one q", "t1"),
            _cmsg("a1", "r1", "assistant", "root one a", "t2"),
            _cmsg("r2", "GONE", "human", "orphan root q", "t3"),   # parent not in export
            _cmsg("a2", "r2", "assistant", "orphan root a", "t4"),
            _cmsg("b1", "a1", "human", "follow up", "t5"),
            _cmsg("old", "b1", "assistant", "ABANDONED", "t6"),
            _cmsg("new", "b1", "assistant", "LIVE longer thread", "t7"),
            _cmsg("cont", "new", "human", "continues under newer", "t8"),
        ]}

    # design_chats/*.json is a DIFFERENT on-disk shape for a real conversation: `messages`
    # instead of `chat_messages`, and content as either a bare string or contentBlocks.
    yield "synthetic-design-chat", {
        "uuid": "d", "title": "Design", "messages": [
            {"uuid": "m1", "role": "user", "content": {"content": "design me a thing"}},
            {"uuid": "m2", "role": "assistant",
             "content": {"contentBlocks": [{"type": "text", "text": "here it is"}]}}]}

    # attachments and files are metadata the renderer must not drop, and a real timestamp
    # rather than the opaque "tN" markers above, so the date path is exercised too.
    #
    # EVERY optional key claude.py:225-262 reads is supplied EXPLICITLY here, including ones
    # a real export often omits (file_uuid below; integration_name / icon_name / id /
    # tool_use_id in the next case). That is not padding — see the KNOWN DIVERGENCE note in
    # adapter-parity.test.ts: for an ABSENT optional the python rail serialises `null` and
    # this rail omits the key, so a fixture that left them out would fail on the
    # serialisation shape and mask the dispatch logic these cases exist to check.
    yield "synthetic-attachments", {
        "uuid": "att", "name": "With files", "created_at": "2026-02-03T04:05:06.789012Z",
        "account": {"uuid": "acct-1"},
        "chat_messages": [
            _cmsg("m1", None, "human", "see attached", "2026-02-03T04:05:06.789012Z",
                  attachments=[{"file_name": "notes.txt", "file_size": 12,
                                "file_type": "text/plain", "extracted_content": "hello"}],
                  files=[{"file_name": "pic.png", "file_uuid": "synthetic-file-uuid"}]),
            _cmsg("m2", "m1", "assistant", "got it", "2026-02-03T04:05:07.000000Z"),
        ]}

    # a tool_use / tool_result pair plus a thinking block: the non-text content types whose
    # dispatch is hand-written on both rails
    yield "synthetic-tool-and-thinking", {
        "uuid": "tool", "name": "Tools", "account": {"uuid": "acct-1"},
        "chat_messages": [
            _cmsg("m1", None, "human", "search it", "t1"),
            {"uuid": "m2", "parent_message_uuid": "m1", "sender": "assistant",
             "created_at": "t2", "attachments": [], "files": [], "text": "",
             "content": [
                 {"type": "thinking", "thinking": "considering the options",
                  "summaries": [{"summary": "weighing it up"}]},
                 {"type": "tool_use", "name": "web_search", "id": "toolu_SYNTH",
                  "input": {"query": "a synthetic query"},
                  "display_content": "Searching", "integration_name": "search",
                  "icon_name": "magnifier"},
                 {"type": "tool_result", "name": "web_search",
                  "content": [{"type": "text", "text": "a synthetic result"}],
                  "display_content": "1 result", "is_error": False,
                  "integration_name": "search", "icon_name": "magnifier",
                  "tool_use_id": "toolu_SYNTH"},
                 {"type": "text", "text": "here is what I found", "citations": []},
             ]},
        ]}


# ------------------------------------------------------------------------------ chatgpt

def _node(nid, parent, kids, role=None, parts=None, ct=1.0, content=None, meta=None):
    m = None
    if role:
        m = {"id": nid, "author": {"role": role}, "create_time": ct,
             "content": content or {"content_type": "text", "parts": parts or []},
             "metadata": meta or {}}
    return {"id": nid, "message": m, "parent": parent, "children": kids}


def chatgpt_cases():
    # current_node absent -> the loader must still find the live leaf, or the whole
    # conversation renders as zero turns
    yield "synthetic-null-current-node", {
        "title": "t", "conversation_id": "x", "current_node": None, "create_time": 1.0,
        "mapping": {
            "r": _node("r", None, ["a"]),
            "a": _node("a", "r", ["b"], "user", ["hello"], 1.0),
            "b": _node("b", "a", [], "assistant", ["hi there"], 2.0)}}

    # a regenerated reply: TWO children of the same user turn, current_node down the
    # second. Only the live one may render, and it must carry branch 2/2.
    yield "synthetic-branch-regeneration", {
        "title": "regen", "conversation_id": "regen-1", "current_node": "b2",
        "create_time": 1700000000.0,
        "mapping": {
            "r": _node("r", None, ["u"]),
            "u": _node("u", "r", ["b1", "b2"], "user", ["ask once"], 1700000000.0),
            "b1": _node("b1", "u", [], "assistant", ["DISCARDED reply"], 1700000001.0),
            "b2": _node("b2", "u", ["u2"], "assistant", ["kept reply"], 1700000002.0),
            "u2": _node("u2", "b2", [], "user", ["and again"], 1700000003.5)}}

    # the content-type dispatch: code, a collapsed thinking block, execution output, a
    # multimodal part, and a message the export marks visually hidden
    yield "synthetic-content-types", {
        "title": "types", "conversation_id": "types-1", "current_node": "n5",
        "create_time": 1700000000.0,
        "mapping": {
            "r": _node("r", None, ["n1"]),
            "n1": _node("n1", "r", ["n2"], "user", ["run it"], 1700000000.0),
            "n2": _node("n2", "n1", ["n3"], "assistant", None, 1700000001.0,
                        content={"content_type": "thoughts",
                                 "thoughts": [{"summary": "plan", "content": "step one"}]}),
            "n3": _node("n3", "n2", ["n4"], "assistant", None, 1700000002.0,
                        content={"content_type": "code", "language": "python",
                                 "text": "print(1)"}),
            "n4": _node("n4", "n3", ["n5"], "tool", None, 1700000003.0,
                        content={"content_type": "execution_output", "text": "1"},
                        meta={"is_visually_hidden_from_conversation": True}),
            "n5": _node("n5", "n4", [], "assistant", None, 1700000004.0,
                        content={"content_type": "multimodal_text", "parts": [
                            {"content_type": "image_asset_pointer",
                             "asset_pointer": "file-service://file-SYNTHETIC",
                             "width": 8, "height": 8},
                            "and a caption"]})}}

    # __project_id is what the projects file contributes; id (not conversation_id) is the
    # older key, and both rails must fall back to it
    yield "synthetic-project-tagged", {
        "title": "tagged", "id": "old-key-1", "current_node": "b",
        "create_time": 1700000000.0, "__project_id": "g-p-SYNTHETIC",
        "mapping": {
            "r": _node("r", None, ["a"]),
            "a": _node("a", "r", ["b"], "user", ["tagged q"], 1700000000.0),
            "b": _node("b", "a", [], "assistant", ["tagged a"], 1700000001.0)}}


# ------------------------------------------------------------------------------- gemini

def gemini_cases():
    recs = [
        {"verb": "Prompted", "prompt": "q1", "response_md": "a1",
         "timestamp_iso": "2026-01-01T10:00:00", "gem": None},
        {"verb": "Used", "title": "Used Canvas", "detail": "d",
         "timestamp_iso": "2026-01-01T10:05:00", "gem": None},
        {"verb": "Prompted", "prompt": "q2", "response_md": "a2",
         "timestamp_iso": "2026-01-01T11:00:00", "gem": "CustomGem"},
    ]
    groups = [{"id": "g1", "title": "First", "turn_idxs": [0, 1]},
              {"id": "g2", "title": "Second", "turn_idxs": [2]}]
    yield "synthetic-grouped", {"records": recs, "groups": groups}

    # the leftover bucket the gap heuristic produces, plus records carrying attachments and
    # a missing timestamp -- the shapes that make a real Takeout export awkward
    recs2 = [
        {"verb": "Prompted", "prompt": "with a file", "response_md": "ok",
         "timestamp_iso": "2026-03-04T05:06:07", "gem": None,
         "attachments": [{"name": "a.pdf"}], "media": [{"name": "b.png"}]},
        {"verb": "Prompted", "prompt": "no timestamp", "response_md": "still rendered",
         "timestamp_iso": "", "gem": None},
    ]
    yield "synthetic-unmatched-bucket", {
        "records": recs2,
        "groups": [{"id": "unmatched", "title": "(unmatched Takeout activity)",
                    "turn_idxs": [0, 1]}]}


def main():
    out = {"claude": [], "chatgpt": [], "gemini": []}

    for name, conv in claude_cases():
        is_dc = claude.is_design_chat(conv)
        parsed = claude.parse_design_chat(conv) if is_dc else claude.parse_conversation(conv)
        out["claude"].append({"name": name, "input": conv,
                              "is_design_chat": is_dc, "ir": ir_dict(parsed)})

    for name, conv in chatgpt_cases():
        out["chatgpt"].append({"name": name, "input": conv,
                               "ir": ir_dict(chatgpt.parse_conversation(conv))})

    for name, payload in gemini_cases():
        convs = gemini.parse_all(payload["records"], payload["groups"])
        out["gemini"].append({"name": name, "records": payload["records"],
                              "groups": payload["groups"],
                              "ir": [ir_dict(c) for c in convs]})

    # newline="\n" and sort_keys: the fixture is committed, so its bytes must be stable
    # across platforms or the CI staleness diff fires on line endings / dict order instead
    # of on a real adapter change.
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(out, fh, ensure_ascii=True, indent=1, sort_keys=True)
        fh.write("\n")
    print("WROTE", OUT, os.path.getsize(OUT), "bytes")
    print("claude", len(out["claude"]), "| chatgpt", len(out["chatgpt"]),
          "| gemini", len(out["gemini"]))


if __name__ == "__main__":
    main()
