/**
 * Adapter cross-language parity: feed each Python adapter's exact input to the JS
 * adapter and assert IDENTICAL IR.
 *
 * This is the gate that reaches the hard logic — Claude's subtree-max active-path
 * walk (the naive version dropped 42 messages on real data), ChatGPT's current_node
 * fallback and branch bookkeeping, the content-type dispatch, epoch→ISO timestamp
 * formatting — which the synthetic renderer fixtures never touch.
 *
 * WHY THIS FILE LOOKS LIKE THIS NOW. It used to be one
 * `describe.skipIf(!present)` over `fixtures/adapter-parity.json`, and that fixture is
 * gitignored (.gitignore:32) and generated by NO workflow. So on every fresh clone and in
 * every CI run the whole suite SKIPPED: it had never executed anywhere except the one
 * machine that had run `tools/gen-adapter-parity.py` by hand, it could not fail, and a gate
 * that cannot fail is indistinguishable from no gate at all. Vitest reported it green.
 *
 * It is now two layers:
 *
 *   1. `fixtures/adapter-parity-synthetic.json` — COMMITTED, corpus-free, produced by the
 *      real Python adapters via `js/test/fixtures/gen-adapter-parity-synthetic.py`. Loaded
 *      WITHOUT an existence guard on purpose: it ships with the clone, so an absent,
 *      truncated or unparseable file is a broken checkout and this file must fail to
 *      collect rather than quietly skip. This layer is what makes the gate real.
 *   2. `fixtures/adapter-parity.json` — the local-only fixture that SAMPLES the owner's
 *      real private corpora. Still optional, still gitignored, never packaged. When it is
 *      present its cases are layered on top and get the real-data check too.
 */
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import * as chatgpt from "../src/adapters/chatgpt.js";
import * as claude from "../src/adapters/claude.js";
import * as gemini from "../src/adapters/gemini.js";
import type { Conversation } from "../src/ir.js";

interface ClaudeCase {
  name: string;
  input: unknown;
  is_design_chat: boolean;
  ir: Conversation;
}
interface ChatgptCase {
  name: string;
  input: Record<string, unknown>;
  ir: Conversation;
}
interface GeminiCase {
  name: string;
  records: Record<string, unknown>[];
  groups: gemini.Group[];
  ir: Conversation[];
}
interface Fx {
  claude: ClaudeCase[];
  chatgpt: ChatgptCase[];
  gemini: GeminiCase[];
}

const fixture = (name: string): string =>
  fileURLToPath(new URL(`./fixtures/${name}`, import.meta.url));

const SYNTHETIC = fixture("adapter-parity-synthetic.json");
const CORPUS = fixture("adapter-parity.json");

/** Committed. Unguarded read — see the header: an absent file is a red gate, not a skip. */
const synthetic: Fx = JSON.parse(readFileSync(SYNTHETIC, "utf8")) as Fx;

const corpusPresent = existsSync(CORPUS);
const corpus: Fx = corpusPresent
  ? (JSON.parse(readFileSync(CORPUS, "utf8")) as Fx)
  : { claude: [], chatgpt: [], gemini: [] };

/** Tag each case with the fixture it came from so a failure names its own source. */
const layered = <T extends { name: string }>(pick: (f: Fx) => T[]): Array<[string, T]> => [
  ...pick(synthetic).map((c): [string, T] => [`[committed] ${c.name}`, c]),
  ...pick(corpus).map((c): [string, T] => [`[local-corpus] ${c.name}`, c]),
];

/** IR round-trips through JSON before comparison so `undefined` vs missing key and
 *  tuple-vs-array shapes match Python's asdict()+json output exactly. */
const norm = (v: unknown): unknown => JSON.parse(JSON.stringify(v));

describe("adapter parity — the committed fixture is a REQUIRED input", () => {
  // ci-hygiene: an empty walk must FAIL CLOSED. A fixture that parsed but contributed no
  // cases would make every describe below vacuously green, which is the exact failure this
  // file is being repaired for — so assert the shape of the input, not just that it loaded.
  it("contributes cases for all three providers", () => {
    expect(synthetic.claude.length).toBeGreaterThan(0);
    expect(synthetic.chatgpt.length).toBeGreaterThan(0);
    expect(synthetic.gemini.length).toBeGreaterThan(0);
  });

  it("is non-trivial", () => {
    const total = synthetic.claude.length + synthetic.chatgpt.length + synthetic.gemini.length;
    expect(total).toBeGreaterThan(3);
  });

  it("reports whether the local real-corpus layer is also active", () => {
    // a visible marker in the report so an absent local fixture is a conscious state. It is
    // NOT a hole any more: the committed layer above ran regardless. Regenerate the local
    // one with `python tools/gen-adapter-parity.py` for the real-data check.
    expect(typeof corpusPresent).toBe("boolean");
  });
});

describe("KNOWN DIVERGENCE — an ABSENT optional field serialises differently", () => {
  /*
   * Found by the new committed cases, which is the first evidence this gate has ever
   * produced. It is NOT reached by the renderer parity fixtures and NOT reached by the
   * local real-corpus layer either: counted by name, that fixture holds 42 `real-claude-*`
   * cases and they all pass, so none of them carries a files/attachment/tool block at all.
   *
   * That count also corrects the record. The commit that added this file (2df58b0) says
   * "all 45 real-claude cases pass" — 45 was never measured and is wrong; 42 is the counted
   * value. The same count turned up something the old gate's reputation did not survive:
   * the local fixture holds ZERO `real-*` chatgpt and ZERO `real-*` gemini cases (44/1/1
   * per provider, of which 4 are the tools generator's own synthetic ones). So even on the
   * one machine where it did run, the "real corpus" check only ever covered Claude. The
   * committed layer is what gives chatgpt and gemini any parity cases at all.
   *
   * Measured. For a claude `files` entry with no `file_uuid`:
   *   python  claude.py:236  data={"file_name": ..., "file_uuid": f.get("file_uuid")}
   *                          -> asdict()+json emits  "file_uuid": null
   *   this rail claude.ts:236 data={file_name: ..., file_uuid: get(f, "file_uuid")}
   *                          -> get() returns undefined, so JSON.stringify DROPS the key
   *
   * So the IR OBJECTS agree — the key is present on both sides and both read falsy — and
   * the divergence exists only at the JSON boundary. Benign today, and that is measured
   * rather than assumed: every consumer of Block.data collapses the two, always as an
   * explicit pair (`v === null || v === undefined` at render_html.ts:53, and
   * `!== undefined && !== null` at render_html.ts:196,207,275 · render_md.ts:115,126,173 ·
   * audit.ts:30). Not one of them can tell null from undefined, and the committed
   * byte-for-byte renderer gate (fixtures/render-parity.json) is green. It would stop being
   * benign the moment this rail serialises IR to JSON the way python's `index` command
   * does, since there the difference is a present-vs-absent key.
   *
   * NOT FIXED HERE: the change belongs in js/src/adapters/claude.ts (`get` returning null,
   * or an explicit `?? null` per optional), which is outside this unit's file scope and is
   * a sibling agent's file. Pinned rather than left as prose so it cannot drift silently.
   *
   * IF THIS TEST GOES RED because the adapter now emits null: that is the fix landing.
   * Delete this describe block and drop the explicit optional keys from
   * fixtures/gen-adapter-parity-synthetic.py, then regenerate.
   */
  const withoutFileUuid = {
    uuid: "div",
    name: "divergence probe",
    chat_messages: [
      {
        uuid: "m1", parent_message_uuid: null, sender: "human", created_at: "t1",
        content: [{ type: "text", text: "here", citations: [] }],
        attachments: [], files: [{ file_name: "pic.png" }], text: "",
      },
    ],
  };

  it("keeps the key on the object but drops it from JSON, where python keeps null", () => {
    const data = claude.parseConversation(withoutFileUuid).turns[0].blocks[0].data as Record<
      string,
      unknown
    >;
    expect(Object.hasOwn(data, "file_uuid")).toBe(true); // object shapes DO agree
    expect(data.file_uuid).toBeUndefined(); // python has None here
    expect(Object.hasOwn(norm(data) as Record<string, unknown>, "file_uuid")).toBe(false);
  });
});

describe("adapter parity (claude)", () => {
  for (const [name, c] of layered((f) => f.claude)) {
    it(name, () => {
      const parsed = c.is_design_chat
        ? claude.parseDesignChat(c.input as Record<string, unknown>)
        : claude.parseConversation(c.input);
      expect(norm(parsed)).toEqual(norm(c.ir));
    });
  }
});

describe("adapter parity (chatgpt)", () => {
  for (const [name, c] of layered((f) => f.chatgpt)) {
    it(name, () => {
      expect(norm(chatgpt.parseConversation(c.input))).toEqual(norm(c.ir));
    });
  }
});

describe("adapter parity (gemini)", () => {
  for (const [name, c] of layered((f) => f.gemini)) {
    it(name, () => {
      expect(norm(gemini.parseAll(c.records, c.groups))).toEqual(norm(c.ir));
    });
  }
});
